import os

content = (
    "import React from \"react\";\n"
    "import { Facebook, Youtube, Mail, Tv, Sparkles, Heart, Clock, MapPin, CreditCard } from \"lucide-react\";\n"
    "import { Link } from \"react-router-dom\";\n"
    "import { useTranslation } from \"react-i18next\";\n"
    "\n"
    "export function Footer() {\n"
    "  const { t, i18n } = useTranslation();\n"
    "\n"
    "  return (\n"
    "    <footer className=\"bg-alabaster border-t border-[#AE8F05]/20 pt-16 pb-8 text-warm-slate relative overflow-hidden\">\n"
    "      <div className=\"absolute bottom-0 left-1/2 -translate-x-1/2 w-full h-64 bg-gradient-to-t from-champagne-pearl/50 to-transparent pointer-events-none\" />\n"
    "      <div className=\"max-w-7xl mx-auto px-4 md:px-8 relative z-10\">\n"
    "        <div className=\"grid grid-cols-1 md:grid-cols-2 lg:grid-cols-5 gap-10 mb-12\">\n"
    "\n"
    "          {/* Brand */}\n"
    "          <div className=\"space-y-4 lg:col-span-1\">\n"
    "            <div className=\"flex items-center space-x-3\">\n"
    "              <div className=\"p-1 rounded-full bg-gradient-to-tr from-[#D4AF37] to-[#AE8F05]\">\n"
    "                <img\n"
    "                  src=\"https://res.cloudinary.com/dj3wxiznw/image/upload/v1775806075/IMG_20250911_220600_711-removebg-preview_hesfjl.png\"\n"
    "                  onError={(e) => {\n"
    "                    const target = e.currentTarget as HTMLImageElement;\n"
    "                    if (!target.src.endsWith(\"/IMG_20250911_220600_711-removebg-preview.png\")) {\n"
    "                      target.src = \"/IMG_20250911_220600_711-removebg-preview.png\";\n"
    "                    }\n"
    "                  }}\n"
    "                  alt=\"Mission For Nation Logo\"\n"
    "                  className=\"w-9 h-9 object-contain bg-white rounded-full p-0.5\"\n"
    "                />\n"
    "              </div>\n"
    "              <span className=\"font-serif font-extrabold text-lg text-warm-slate\">\n"
    "                {i18n.language === \"am\" ? \"\u1270\u120d\u12d5\u12ae \u1208\u1275\u12cd\u120d\u12f5\" : \"MISSION FOR NATION\"}\n"
    "              </span>\n"
    "            </div>\n"
    "            <p className=\"text-[#5C5854] text-sm leading-relaxed\">\n"
    "              {t(\"footer.description\") || \"30 Years of divine vision, establishing churches, training pastors, and reaching millions through 7 Spirit TV broadcast.\"}\n"
    "            </p>\n"
    "            <div className=\"inline-flex items-center space-x-2 px-3 py-1 bg-[#FFFFF0] border border-[#AE8F05]/30 rounded-full text-xs font-semibold text-sacred-gold shadow-sm\">\n"
    "              <Sparkles className=\"w-3.5 h-3.5\" />\n"
    "              <span>30th Anniversary Golden Jubilee (1996 - 2026)</span>\n"
    "            </div>\n"
    "          </div>\n"
    "\n"
    "          {/* Quick Links */}\n"
    "          <div>\n"
    "            <h4 className=\"font-serif font-bold mb-6 uppercase tracking-wider text-sm text-warm-slate\">\n"
    "              {t(\"footer.quickLinks\") || \"Quick Links\"}\n"
    "            </h4>\n"
    "            <ul className=\"space-y-3 text-sm\">\n"
    "              <li><Link to=\"/\" className=\"text-[#5C5854] hover:text-sacred-gold font-medium transition-colors\">{t(\"nav.home\")}</Link></li>\n"
    "              <li><Link to=\"/about\" className=\"text-[#5C5854] hover:text-sacred-gold font-medium transition-colors\">{t(\"nav.about\")}</Link></li>\n"
    "              <li><Link to=\"/services\" className=\"text-[#5C5854] hover:text-sacred-gold font-medium transition-colors\">{t(\"nav.services\")}</Link></li>\n"
    "              <li><Link to=\"/gallery\" className=\"text-[#5C5854] hover:text-sacred-gold font-medium transition-colors\">{t(\"nav.gallery\")}</Link></li>\n"
    "              <li>\n"
    "                <a href=\"#giving\" className=\"text-sacred-gold font-semibold hover:underline flex items-center space-x-1\">\n"
    "                  <Heart className=\"w-3.5 h-3.5 mr-1\" />\n"
    "                  <span>Give to 7 Spirit TV</span>\n"
    "                </a>\n"
    "              </li>\n"
    "            </ul>\n"
    "          </div>\n"
    "\n"
    "          {/* Donate */}\n"
    "          <div id=\"giving\">\n"
    "            <h4 className=\"font-serif font-bold mb-2 uppercase tracking-wider text-sm text-warm-slate flex items-center gap-2\">\n"
    "              <Heart className=\"w-4 h-4 text-[#D4AF37] animate-pulse\" />\n"
    "              Support the Ministry\n"
    "            </h4>\n"
    "            <p className=\"text-xs text-[#AE8F05] font-semibold mb-4\">\u12a0\u1308\u120d\u130d\u120e\u1271\u1295 \u1208\u1218\u12f0\u1308\u1348 (To Support)</p>\n"
    "            <ul className=\"space-y-3 text-sm\">\n"
    "              <li className=\"flex items-start gap-3\">\n"
    "                <CreditCard className=\"w-4 h-4 text-[#D4AF37] mt-0.5 flex-shrink-0\" />\n"
    "                <div>\n"
    "                  <p className=\"font-semibold text-[#2C2A28] text-xs\">Commercial Bank of Ethiopia (CBE)</p>\n"
    "                  <p className=\"text-[#5C5854] font-mono text-sm tracking-wider select-all\">1000450749738</p>\n"
    "                </div>\n"
    "              </li>\n"
    "              <li className=\"flex items-start gap-3\">\n"
    "                <CreditCard className=\"w-4 h-4 text-[#D4AF37] mt-0.5 flex-shrink-0\" />\n"
    "                <div>\n"
    "                  <p className=\"font-semibold text-[#2C2A28] text-xs\">Berhan Bank</p>\n"
    "                  <p className=\"text-[#5C5854] font-mono text-sm tracking-wider select-all\">2600050004252</p>\n"
    "                </div>\n"
    "              </li>\n"
    "            </ul>\n"
    "          </div>\n"
    "\n"
    "          {/* Schedule */}\n"
    "          <div>\n"
    "            <h4 className=\"font-serif font-bold mb-6 uppercase tracking-wider text-sm text-warm-slate flex items-center gap-2\">\n"
    "              <Clock className=\"w-4 h-4 text-[#D4AF37]\" />\n"
    "              Service Times\n"
    "            </h4>\n"
    "            <p className=\"text-[10px] text-[#AE8F05] uppercase tracking-widest mb-3 font-semibold\">Ethiopian Local Time</p>\n"
    "            <ul className=\"space-y-2 text-sm mb-5\">\n"
    "              <li className=\"flex items-center justify-between gap-2\">\n"
    "                <span className=\"text-[#5C5854] font-medium\">Tuesday</span>\n"
    "                <span className=\"text-[#2C2A28] font-semibold bg-[#F7E7CE] px-2 py-0.5 rounded-md text-xs\">10:30 - 1:30</span>\n"
    "              </li>\n"
    "              <li className=\"flex items-center justify-between gap-2\">\n"
    "                <span className=\"text-[#5C5854] font-medium\">Wednesday</span>\n"
    "                <span className=\"text-[#2C2A28] font-semibold bg-[#F7E7CE] px-2 py-0.5 rounded-md text-xs\">8:30 - 1:30</span>\n"
    "              </li>\n"
    "              <li className=\"flex items-center justify-between gap-2\">\n"
    "                <span className=\"text-[#5C5854] font-medium\">Sunday</span>\n"
    "                <span className=\"text-[#2C2A28] font-semibold bg-[#F7E7CE] px-2 py-0.5 rounded-md text-xs\">2:00 - 7:30</span>\n"
    "              </li>\n"
    "            </ul>\n"
    "            <div className=\"flex items-start gap-2 text-xs text-[#5C5854] leading-relaxed\">\n"
    "              <MapPin className=\"w-4 h-4 text-[#D4AF37] mt-0.5 flex-shrink-0\" />\n"
    "              <span>Bulgaria Mebrat to Cherkos, next to My Dream Apartment / Jambo Real Estate, Addis Ababa</span>\n"
    "            </div>\n"
    "          </div>\n"
    "\n"
    "          {/* Connect */}\n"
    "          <div>\n"
    "            <h4 className=\"font-serif font-bold mb-6 uppercase tracking-wider text-sm text-warm-slate\">\n"
    "              {t(\"footer.connect\") || \"Connect With Us\"}\n"
    "            </h4>\n"
    "            <ul className=\"space-y-4 text-sm\">\n"
    "              <li className=\"flex items-center gap-3 text-[#5C5854]\">\n"
    "                <Mail className=\"w-5 h-5 text-sacred-gold flex-shrink-0\" />\n"
    "                <a href=\"mailto:7spiritstv@gmail.com\" className=\"hover:text-sacred-gold transition-colors font-medium\">7spiritstv@gmail.com</a>\n"
    "              </li>\n"
    "              <li className=\"flex items-center gap-3 text-[#5C5854]\">\n"
    "                <Tv className=\"w-5 h-5 text-sacred-gold flex-shrink-0\" />\n"
    "                <span className=\"font-medium\">7 Spirit TV Broadcast Center</span>\n"
    "              </li>\n"
    "              <li className=\"flex items-center gap-3 text-[#5C5854]\">\n"
    "                <Facebook className=\"w-5 h-5 text-sacred-gold flex-shrink-0\" />\n"
    "                <a href=\"https://www.facebook.com/7spiritstv\" target=\"_blank\" rel=\"noopener noreferrer\" className=\"hover:text-sacred-gold transition-colors font-medium\">7 Spirits TV Official</a>\n"
    "              </li>\n"
    "              <li className=\"flex items-center gap-3 text-[#5C5854]\">\n"
    "                <Youtube className=\"w-5 h-5 text-sacred-gold flex-shrink-0\" />\n"
    "                <a href=\"https://www.youtube.com/channel/UCFVGPq_UQ5ESFkmTQCSXeBQ\" target=\"_blank\" rel=\"noopener noreferrer\" className=\"hover:text-sacred-gold transition-colors font-medium\">7spirits TV Channel</a>\n"
    "              </li>\n"
    "            </ul>\n"
    "          </div>\n"
    "\n"
    "        </div>\n"
    "\n"
    "        <div className=\"border-t border-[#AE8F05]/20 pt-8 flex flex-col md:flex-row justify-between items-center gap-4 text-xs text-[#5C5854]\">\n"
    "          <p className=\"font-medium\">\n"
    "            &copy; 1996 - 2026 Mission For Nation Church. All rights reserved. 30th Anniversary Edition.\n"
    "          </p>\n"
    "          <div className=\"flex gap-6 font-medium\">\n"
    "            <a href=\"#\" className=\"hover:text-sacred-gold transition-colors\">Privacy Policy</a>\n"
    "            <a href=\"#\" className=\"hover:text-sacred-gold transition-colors\">Terms of Service</a>\n"
    "          </div>\n"
    "        </div>\n"
    "      </div>\n"
    "    </footer>\n"
    "  );\n"
    "}\n"
)

filepath = os.path.join('src', 'app', 'components', 'Footer.tsx')
with open(filepath, 'w', encoding='utf-8') as f:
    f.write(content)
print('Footer.tsx written successfully, chars:', len(content))
